fixtures:
  symlinks:
    "hiera": "#{source_dir}"
  repositories:
    "inifile":          "git://github.com/puppetlabs/puppetlabs-inifile.git"
    "puppetserver_gem": "git://github.com/puppetlabs/puppetlabs-puppetserver_gem.git"
    "stdlib":           "git://github.com/puppetlabs/puppetlabs-stdlib.git"
